config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :movies
  root :to => redirect('/movies')
  
  get '/find_movies_same_director/:id', to: 'movies#find_movies_same_director', as: 'find_movies_same_director'
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def show
    id = params[:id] # retrieve movie ID from URI route
    @movie = Movie.find(id) # look up movie by unique ID
    # will render app/views/movies/show.<extension> by default
  end

  # def all_ratings
  #   %w(G PG PG-13 NC-17 R)
  # end
  
  def index
    #@movies = Movie.all #first version
    #### Version below is deprecated due to issues on params to_h in current Rails 5  
    #### For more detais, see https://stackoverflow.com/questions/34949505/unable-to-retrieve-hash-values-from-parameter/34951198#34951198?newreg=0d502608c9d148b0893decf2995fe3d2
    # params.permit(:sort, :ratings)
    # sort = params[:sort] || session[:sort]
    # case sort
    # when 'title'
    #   ordering,@title_header = {:title => :asc}, 'hilite'
    # when 'release_date'
    #   ordering,@date_header = {:release_date => :asc}, 'hilite'
    # end
    #  @all_ratings = Movie.all_ratings
    #  #As for Ruby version = 5
    #  @selected_ratings = params.permit([:ratings]).to_h || session.permit([:ratings]).to_h || {}
    #  #As for Ruby version <=4
    #  #@selected_ratings = params[:ratings]|| session[:ratings] || {}

    #  if @selected_ratings == {}
    #    @selected_ratings = Hash[@all_ratings.map {|rating| [rating, rating]}]
    #  end

    #  if params[:sort] != session[:sort] or params[:ratings] != session[:ratings]
    #    session[:sort] = sort
    #    session[:ratings] = @selected_ratings
    #    redirect_to :sort => sort, :ratings => @selected_ratings and return
    #  end
    # #@movies = Movie.order(ordering)
    # @movies = Movie.where(rating: @selected_ratings.keys).order(ordering)
  
    @movies = Movie.all 
    sort = params[:sort_by] || session[:sort_by]
    case sort
    when 'title'
      ordering, @title_header = {:title => :asc}, 'hilite'
    when 'release_date'
      ordering, @date_header = {:release_date => :asc}, 'hilite'
    end

    @all_ratings = Movie.all_ratings
    params.permit([:ratings]).to_h

    if (params[:sort_by])
      session[:sort_by] = params[:sort_by]
      if (session[:ratings])
        @selected_ratings = session[:ratings]
      end
    elsif (params[:ratings])
      session[:ratings] = params[:ratings]
      @selected_ratings = params[:ratings]
    else
      session[:sort_by] = nil
      session[:ratings] = nil
      @selected_ratings = Hash[@all_ratings.map {|rating| [rating, rating]}]
    end
    @movies = Movie.where(rating: @selected_ratings.keys).order(ordering)
  end

  def new
    # default: render 'new' template
  end

  def create
    params.permit!
    @movie = Movie.create(params[:movie])
    flash[:notice] = "#{@movie.title} was successfully created."
    redirect_to movies_path
  end

  def movie_params
    params.require(:movie).permit(:title, :director, :rating, :description, :release_date)
  end

  def edit
    @movie = Movie.find params[:id]
  end

  def update
    params.permit!
    @movie = Movie.find params[:id]
    @movie.update(params[:movie])
    flash[:notice] = "#{@movie.title} was successfully updated."
    redirect_to movie_path(@movie)
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    flash[:notice] = "Movie '#{@movie.title}' deleted."
    redirect_to movies_path
  end

  def find_movies_same_director
    @movie = Movie.find(params[:id])
    @movies_same_director = Movie.where(:director => @movie.director)
  end

end

app/views/movies/edit.html.haml
-# edit.html.haml using partial

%h1 Edit Existing Movie

= form_tag movie_path(@movie), :method => :put do

  = label :movie, :title, 'Title'
  = text_field :movie, 'title'

  = label :movie, :director, 'Director'
  = text_field :movie, 'director'
  
  = label :movie, :rating, 'Rating'
  = select :movie, :rating, ['G','PG','PG-13','R','NC-17']

  = label :movie, :release_date, 'Released On'
  = date_select :movie, :release_date

  = submit_tag 'Update Movie Info'

app/views/movies/find_movies_same_director.html.haml
-#  This file is app/views/movies/find_movies_same_director.html.haml
%h1 Movies with same director

%table#movies
  %thead
    %tr
      /As for previous version of Ruby @selected_ratings was not converted to hash, but to a string.
      /%th{:class => @title_header}= link_to 'Movie Title', movies_path(:sort => 'title', :ratings => @selected_ratings), :id => 'title_header'
      /%th Rating
      /%th{:class => @date_header}= link_to 'Release Date', movies_path(:sort => 'release_date', :ratings => @selected_ratings), :id => 'release_date_header'
      %th= link_to 'Movie Title', controller: 'movies', action: 'index', id: 'title_header', sort_by: 'title'
      %th Rating
      %th= link_to 'Release Date', controller: 'movies', action: 'index', id: 'release_date_header', sort_by: 'release_date'
      %th More Info
  %tbody
    - @movies_same_director.each do |movie|
      %tr
        %td= movie.title 
        %td= movie.rating
        %td= movie.release_date
        %td= link_to "More about #{movie.title}", movie_path(movie)

= link_to 'Back to movie list', movies_path

app/views/movies/new.html.haml
%h1 Create New Movie

= form_tag movies_path do

  = label :movie, :title, 'Title'
  = text_field :movie, 'title'

  = label :movie, :director, 'Director'
  = text_field :movie, 'director'

  = label :movie, :rating, 'Rating'
  = select :movie, :rating, ['G','PG','PG-13','R','NC-17']

  = label :movie, :release_date, 'Released On'
  = date_select :movie, :release_date

  = submit_tag 'Save Changes'

app/views/movies/show.html.haml
-# in app/views/movies/show.html.haml

%h2 Details about #{@movie.title}

%ul#details
  %li
    Director:
    = @movie.director
  %li
    Rating:
    = @movie.rating
  %li
    Released on:
    = @movie.release_date.strftime("%B %d, %Y")

%h3 Description:

%p#description= @movie.description

= link_to 'Edit', edit_movie_path(@movie)
= button_to 'Delete', movie_path(@movie), :method => :delete, :confirm => 'Are you sure?'
= link_to 'Back to movie list', movies_path
%br
= link_to 'Find Movies With Same Director', find_movies_same_director_path(@movie)